CREATE TABLE `perpic` (
  `id` INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  `name` VARCHAR(20) DEFAULT NULL,
  `description` VARCHAR(100) COLLATE utf8_general_ci DEFAULT NULL,
  `url` VARCHAR(200) COLLATE utf8_general_ci DEFAULT NULL,
  `time` DATE DEFAULT NULL,
  PRIMARY KEY (`id`) COMMENT ''
) ENGINE=InnoDB
CHECKSUM=0
DELAY_KEY_WRITE=0
PACK_KEYS=0
AUTO_INCREMENT=0
AVG_ROW_LENGTH=0
MIN_ROWS=0
MAX_ROWS=0
ROW_FORMAT=DEFAULT
KEY_BLOCK_SIZE=0
CHARACTER SET 'utf8' COLLATE 'utf8_general_ci';